import { Adjustments, defaultAdjustments, PresetName } from "./types";

export const presets: Record<PresetName, Partial<Adjustments>> = {
  "ai-auto": {},
  natural: {
    contrast: 5,
    highlights: -10,
    shadows: 15,
    vibrance: 8,
    clarity: 5,
    sharpness: 10,
  },
  cinematic: {
    contrast: 20,
    highlights: -15,
    shadows: -10,
    temperature: 8,
    saturation: -10,
    fade: 10,
    vignette: 25,
  },
  clean: {
    exposure: 5,
    contrast: -5,
    highlights: -20,
    shadows: 20,
    saturation: -5,
    clarity: 10,
    noiseReduction: 20,
  },
  portrait: {
    exposure: 5,
    contrast: 5,
    highlights: -15,
    shadows: 10,
    temperature: 3,
    saturation: -5,
    vibrance: 10,
    clarity: -5,
    sharpness: 15,
    noiseReduction: 15,
  },
  landscape: {
    contrast: 15,
    highlights: -20,
    shadows: 25,
    vibrance: 15,
    clarity: 20,
    sharpness: 15,
    saturation: 10,
  },
  product: {
    exposure: 5,
    contrast: 10,
    highlights: -5,
    whites: 10,
    sharpness: 20,
    clarity: 15,
    noiseReduction: 10,
  },
  social: {
    exposure: 8,
    contrast: 10,
    highlights: -10,
    shadows: 15,
    vibrance: 15,
    clarity: 10,
    sharpness: 10,
  },
  night: {
    exposure: 15,
    shadows: 30,
    blacks: 10,
    noiseReduction: 30,
    sharpness: 10,
    vibrance: 5,
  },
  lowlight: {
    exposure: 20,
    shadows: 25,
    highlights: -10,
    noiseReduction: 25,
    clarity: 10,
    vibrance: 5,
  },
  oldphoto: {
    exposure: 5,
    contrast: 10,
    highlights: -15,
    shadows: 20,
    noiseReduction: 20,
    sharpness: 15,
    vibrance: 10,
    saturation: 5,
  },
};

export function applyPreset(preset: PresetName): Adjustments {
  return { ...defaultAdjustments, ...presets[preset] };
}
